version: "3.8"

services:
  web:
    build: ./web
    restart: always
    ports:
      - '8081:80'
    volumes:
      - ./web:/var/www/html
    links:
      - db

  db:
    build: ./database
    restart: always
    volumes:
      - ./database/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: appDB
      MYSQL_USER: argoc
      MYSQL_PASSWORD: 123
